image: laravelsail/php82-composer

stages:
  - setup
  - test
  - deploy

variables:
  MYSQL_DATABASE: onlinestore_test
  MYSQL_ROOT_PASSWORD: root
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: 3306
  DB_DATABASE: $MYSQL_DATABASE
  DB_USERNAME: root
  DB_PASSWORD: root
  APP_ENV: testing

services:
  - mysql:8.0

cache:
  paths:
    - vendor/
    - node_modules/

before_script:
  # Update and install required libraries
  - apt-get update -yqq
  - apt-get install -y libgd-dev libzip-dev libpng-dev zlib1g-dev
  # Install PHP extensions
  - docker-php-ext-install gd pdo pdo_mysql zip
  # Set up the environment
  - cp .env.example .env
  - composer install --prefer-dist --no-progress
  - php artisan key:generate
  - php artisan migrate:fresh --force  # Changed from migrate to fresh
  - composer dump-autoload  # Moved after migrations

setup:
  stage: setup
  script:
    - echo "✅ Setup stage completed."

test:
  stage: test
  script:
    - vendor/bin/phpunit --testsuite=Feature --testsuite=Unit
  artifacts:
    when: always
    paths:
      - storage/logs
    expire_in: 1 week

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "🚀 Deploy stage (manual setup required)."