stages:
  - setup
  - test
  - deploy

variables:
  MYSQL_DATABASE: onlinestore_test
  MYSQL_ROOT_PASSWORD: root
  DB_CONNECTION: mysql
  DB_HOST: mysql
  DB_PORT: 3306
  DB_DATABASE: $MYSQL_DATABASE
  DB_USERNAME: root
  DB_PASSWORD: root

services:
  - mysql:8.0

cache:
  paths:
    - vendor/
    - node_modules/

before_script:
  # Install dependencies
  - composer install --prefer-dist --no-progress --no-suggest
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate --force

setup:
  stage: setup
  script:
    - echo "Setup stage completed."

test:
  stage: test
  script:
    - php artisan test
  artifacts:
    when: always
    paths:
      - storage/logs
    expire_in: 1 week

deploy:
  stage: deploy
  only:
    - main
  script:
    - echo "Deploy stage (manual setup required)."