version: "3.8"

services:
    # Laravel application container
    app:
        build: .
        container_name: laravel-app
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app-network
        depends_on:
            - db
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=online_stoore_db
            - DB_USERNAME=online_stoore_db
            - DB_PASSWORD=online_store_password
        ports:
            - "8080:80"

    # MySQL database container
    db:
        image: mysql:5.7
        container_name: mysql-db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: online_store_password
            MYSQL_DATABASE: online_stoore_db
            MYSQL_USER: your_db_username
            MYSQL_PASSWORD: online_store_password
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - app-network
        ports:
            - "3306:3306"

    # Nginx container (optional for serving Laravel)
    nginx:
        image: nginx:latest
        container_name: nginx-server
        restart: always
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        ports:
            - "80:80"
        networks:
            - app-network
        depends_on:
            - app

volumes:
    db-data:

networks:
    app-network:
        driver: bridge
